export { DashboardPage } from './DashboardPage';
export { SearchPage } from './SearchPage';
export { CandidatesPage } from './CandidatesPage';
export { CandidateProfilePage } from './CandidateProfilePage';
export { CandidateFormPage } from './CandidateFormPage';
export { RequirementsPage } from './RequirementsPage';
export { RequirementDetailPage } from './RequirementDetailPage';
export { RequirementFormPage } from './RequirementFormPage';
export { InterviewsPage } from './InterviewsPage';
export { CustomerAssessmentsPage } from './CustomerAssessmentsPage';
export { ClientMeetingsPage } from './ClientMeetingsPage';
export { CustomersPage } from './CustomersPage';
export { ContractsPage } from './ContractsPage';
export { ConsultantsPage, ConsultantProfilePage } from './ConsultantsPage';
export { MissionsPage } from './MissionsPage';
export { OrganisationPage } from './OrganisationPage';
export { SettingsPage } from './SettingsPage';
export { LoginPage } from './LoginPage';
